[package]
name = "zed-which-key"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.100"
gpui = "0.1.0-alpha.19"
log = "0.4.29"
zed_extension_api = "0.7.0"
